### ISSUE TITLE
Can't read anything from $getItem()

### ISSUE THREAD

**Issue by anlek** [shidianxia/vue-localforage#1]
I've tried a bunch of ways to do this and can't seem to get this to work. 
I checked in the console and the item gets saved in localstore, but it doesn't want to read back out:
![image](https://cloud.githubusercontent.com/assets/11052/16181770/9292f8b6-3653-11e6-86a4-a3cf9dd77561.png)

Here is localstore:
![image](https://cloud.githubusercontent.com/assets/11052/16181778/b9d815d2-3653-11e6-992a-eefd5b11ea7d.png)

**Comment by shidianxia** [comment]
This function does not work correctly. I will try to fix it.

**Comment by anlek** [comment]
This has been fixed

**Comment by Oscarato** [comment]
and the solution? :/
