### ISSUE TITLE
Version numbers not updated

### ISSUE THREAD

**Issue by anlek** [shidianxia/vue-localforage#3]
Hey, just a small issue, but the version number in the file still states `VueLocalForage.version = '0.2.0'` even though on Github comments it states version 0.2.3.

Thanks! :)

**Comment by anlek** [comment]
Also, this might be a good time to release 0.2.4 with the callback bug fix (as I'm still overwriting your live implementation with the fix in my code).
Thanks again for a very useful library!

**Comment by shidianxia** [comment]
Thanks! Also updated on NPM.
