### ISSUE TITLE
Error: No available storage method found

### ISSUE THREAD

**Issue by CDuane** [shidianxia/vue-localforage#4]
Hi, I am using this with Vue Nuxt and it gives me an error when I first visit my website.

`(node:13120) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2):
 Error: No available storage method found.  
(node:13120) DeprecationWarning: Unhandled promise rejections are deprecated. In the future,
promise rejections that are not handled will terminate the Node.js process with a non-zero ex
it code.
`

Do you have any idea why this may be happening please?
Thanks.

**Comment by shidianxia** [comment]
I guess it's a localForage issue. Maybe your code is executed before the driver initialization. How about using `localforage.ready()` ?
